# Generated by Django 4.0.4 on 2022-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('distance', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
