# Generated by Django 4.0.4 on 2022-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_table_options_alter_table_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
